services:
  cloud-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - '3000'
    depends_on:
      cloud-db:
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - proxy

  cloud-db:
    image: postgres:17
    restart: always
    expose:
      - '5432'
    env_file:
      - .env
    volumes:
      - cloud-db:/var/lib/postgresql/data
    networks:
      - proxy      

volumes:
  cloud-db:

networks:
  proxy:
    external: true  
