services:
  cloud-db:
    image: postgres:17
    restart: always
    ports:
      - '5434:5432'
    env_file:
      - .env
    volumes:
      - cloud-db:/var/lib/postgresql/data

volumes:
  cloud-db:
