services:
  cloud-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - '3000'
    depends_on:
      - cloud-db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - proxy

  cloud-db:
    image: postgres:17
    restart: always
    expose:
      - '5432'
    volumes:
      - cloud-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - proxy      

volumes:
  cloud-db:

networks:
  proxy:
    external: true  
