services:
  cloud-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - nest-postgres
    env_file:
      - .env

  cloud-db:
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - cloud-db:/var/lib/postgresql/data

volumes:
  cloud-db:
