@echo off
echo Starting production deployment...

echo Applying database migrations...
call npm run migrate:deploy
if %errorlevel% neq 0 exit /b %errorlevel%

echo Generating Prisma client...
call npm run prisma:generate
if %errorlevel% neq 0 exit /b %errorlevel%

echo Starting application...
call npm run start:prod
